name: movie_app
packages:
  - core/**
  - features/**

command:
  bootstrap:
    environment:
      sdk: ^3.7.2

    dependencies:
      dio: ^5.8.0+1 

    dev_dependencies:
      flutter_lints: ^5.0.0